//ITEMS
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';



//UNITS
export const DELETE_UNIT_REQUEST = 'DELETE_UNIT_REQUEST';
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS';
export const DELETE_UNIT_FAILURE = 'DELETE_UNIT_FAILURE';

export const FIND_UNIT_REQUEST = 'FIND_UNIT_REQUEST';
export const FIND_UNIT_SUCCESS = 'FIND_UNIT_SUCCESS';
export const FIND_UNIT_FAILURE = 'FIND_UNIT_FAILURE';

export const FIND_UNITS_REQUEST = 'FIND_UNITS_REQUEST';
export const FIND_UNITS_SUCCESS = 'FIND_UNITS_SUCCESS';
export const FIND_UNITS_FAILURE = 'FIND_UNITS_FAILURE';

export const ADD_UNIT_REQUEST = 'ADD_UNIT_REQUEST';
export const ADD_UNIT_SUCCESS = 'ADD_UNIT_SUCCESS';
export const ADD_UNIT_FAILURE = 'ADD_UNIT_FAILURE';

export const UPDATE_UNIT_REQUEST = 'UPDATE_UNIT_REQUEST';
export const UPDATE_UNIT_SUCCESS = 'UPDATE_UNIT_SUCCESS';
export const UPDATE_UNIT_FAILURE = 'UPDATE_UNIT_FAILURE';
