//ITEMS
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEM_IMAGE_REQUEST = 'FIND_ITEM_IMAGE_REQUEST';
export const FIND_ITEM_IMAGE_SUCCESS = 'FIND_ITEM_IMAGE_SUCCESS';
export const FIND_ITEM_IMAGE_FAILURE = 'FIND_ITEM_IMAGE_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const UPLOAD_ITEM_IMAGE_REQUEST = 'UPLOAD_ITEM_IMAGE_REQUEST';
export const UPLOAD_ITEM_IMAGE_SUCCESS = 'UPLOAD_ITEM_IMAGE_SUCCESS';
export const UPLOAD_ITEM_IMAGE_FAILURE = 'UPLOAD_ITEM_IMAGE_FAILURE';

export const DELETE_ITEM_IMAGE_REQUEST = 'DELETE_ITEM_IMAGE_REQUEST';
export const DELETE_ITEM_IMAGE_SUCCESS = 'DELETE_ITEM_IMAGE_SUCCESS';
export const DELETE_ITEM_IMAGE_FAILURE = 'DELETE_ITEM_IMAGE_FAILURE';



//UNITS
export const DELETE_UNIT_REQUEST = 'DELETE_UNIT_REQUEST';
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS';
export const DELETE_UNIT_FAILURE = 'DELETE_UNIT_FAILURE';

export const FIND_UNIT_REQUEST = 'FIND_UNIT_REQUEST';
export const FIND_UNIT_SUCCESS = 'FIND_UNIT_SUCCESS';
export const FIND_UNIT_FAILURE = 'FIND_UNIT_FAILURE';

export const FIND_UNITS_REQUEST = 'FIND_UNITS_REQUEST';
export const FIND_UNITS_SUCCESS = 'FIND_UNITS_SUCCESS';
export const FIND_UNITS_FAILURE = 'FIND_UNITS_FAILURE';

export const ADD_UNIT_REQUEST = 'ADD_UNIT_REQUEST';
export const ADD_UNIT_SUCCESS = 'ADD_UNIT_SUCCESS';
export const ADD_UNIT_FAILURE = 'ADD_UNIT_FAILURE';

export const UPDATE_UNIT_REQUEST = 'UPDATE_UNIT_REQUEST';
export const UPDATE_UNIT_SUCCESS = 'UPDATE_UNIT_SUCCESS';
export const UPDATE_UNIT_FAILURE = 'UPDATE_UNIT_FAILURE';


//STOCKS
export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_FAILURE = 'DELETE_STOCK_FAILURE';

export const FIND_STOCK_REQUEST = 'FIND_STOCK_REQUEST';
export const FIND_STOCK_SUCCESS = 'FIND_STOCK_SUCCESS';
export const FIND_STOCK_FAILURE = 'FIND_STOCK_FAILURE';

export const FIND_STOCKS_REQUEST = 'FIND_STOCKS_REQUEST';
export const FIND_STOCKS_SUCCESS = 'FIND_STOCKS_SUCCESS';
export const FIND_STOCKS_FAILURE = 'FIND_STOCKS_FAILURE';

export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_FAILURE = 'ADD_STOCK_FAILURE';

export const UPDATE_STOCK_REQUEST = 'UPDATE_STOCK_REQUEST';
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS';
export const UPDATE_STOCK_FAILURE = 'UPDATE_STOCK_FAILURE';

export const SUMMARY_STOCKS_REQUEST = 'SUMMARY_STOCKS_REQUEST';
export const SUMMARY_STOCKS_SUCCESS = 'SUMMARY_STOCKS_SUCCESS';
export const SUMMARY_STOCKS_FAILURE = 'SUMMARY_STOCKS_FAILURE';




//TRANSACTIONS
export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FIND_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FIND_TRANSACTIONS_FAILURE';

export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAILURE = 'ADD_TRANSACTION_FAILURE';

export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILURE = 'UPDATE_TRANSACTION_FAILURE';

export const SUMMARY_TRANSACTIONS_REQUEST = 'SUMMARY_TRANSACTIONS_REQUEST';
export const SUMMARY_TRANSACTIONS_SUCCESS = 'SUMMARY_TRANSACTIONS_SUCCESS';
export const SUMMARY_TRANSACTIONS_FAILURE = 'SUMMARY_TRANSACTIONS_FAILURE';


